name: Deploy using GitHub Actions

on: 
  push:
  workflow_dispatch:
    inputs:
      subnetName:
        description: 'Name of the new subnet'
        required: true
        default: 'mySubnet'
      subnetAddressPrefix:
        description: 'Address prefix for the new subnet'
        required: true
        default: '10.29.248.0/24'

jobs:
  lint: 
    uses: ./.github/workflows/lint.yml

  validate: 
    uses: ./.github/workflows/validate.yml  
    with:
      environmentType: dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-to-dev:
    needs: [lint, validate]
    with:
      environmentType: dev
      subnetName: ${{ github.event.inputs.subnetName }}
      subnetAddressPrefix: ${{ github.event.inputs.subnetAddressPrefix }}
    uses: ./.github/workflows/deployInfrastructure.yml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}



      #https://stackoverflow.com/questions/71409950/github-action-how-to-access-the-inputs læs senere